[tool.mypy]
strict = true
exclude = 'venv'

[tool.black]
skip-string-normalization = true
extend-exclude = 'venv'

[tool.pylint.MASTER]
recursive = true
ignore-paths = 'venv'

[tool.pylint."MESSAGES CONTROL"]
disable = [
    'invalid-name',
    'missing-class-docstring',
    'missing-function-docstring',
    'missing-module-docstring',
]
