[tool.black]
skip-string-normalization = true
extend-exclude = 'venv'

[tool.isort]
profile = 'black'
extend_skip = 'venv'

[tool.mypy]
strict = true
exclude = 'venv'

[tool.pylint.MASTER]
max-line-length = 88
recursive = true
ignore-paths = 'venv'

[tool.pylint.messages_control]
disable = [
    'invalid-name',
    'missing-class-docstring',
    'missing-function-docstring',
    'missing-module-docstring',
]
