#!/usr/bin/env python3.12

import subprocess


def main() -> None:
    files = get_staged_files()
    check_format(files)


def get_staged_files() -> list[str]:
    proc = subprocess.run(
        ['git', 'diff', '--name-only', '--cached'],
        check=True,
        capture_output=True,
        text=True,
    )
    return [f for f in proc.stdout.strip().split('\n') if f]


def check_format(files: list[str]) -> None:
    if not files:
        return
    subprocess.run(['check-format', '-q'] + files, check=False)


if __name__ == '__main__':
    main()
