#!/bin/bash

# Colors for ls, grep and friends
alias    ls='ls    --color=auto -F'
alias  grep='grep  --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Prompt before overwriting for mv and cp
alias mv='mv -i'
alias cp='cp -i'

# Python tools
alias flake8="run-venv flake8 --config ~/.flake8"
alias mypy="run-venv mypy --config ~/.pyproject.toml"
alias pylint="run-venv pylint --rcfile ~/.pyproject.toml"
alias black="run-venv black --config ~/.pyproject.toml"
alias isort="run-venv isort --settings-path ~/.pyproject.toml"
