#!/bin/bash

# Run in vi mode
set -o vi

# 256 colors
case $TERM in
xterm)  TERM=xterm-256color;;
screen) TERM=screen-256color;;
esac

# check the window size after each command
shopt -s checkwinsize

# Remove duplicates, large history
HISTCONTROL=ignoreupds:erasedups
HISTSIZE=10000
HISTFILESIZE=10000

# append to the history file, don't overwrite it
shopt -s histappend
shopt -s histverify

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# Colors
# gcc
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
# ls
eval $(dircolors -b)

# autocompletion
source /etc/bash_completion
